/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>
#define ALIAS_BASE 0x22000000U
#define BITBAND_BASE 0X20000000U

int main(void)
{
	uint8_t *ptr = (uint8_t*)0x20000200;

	*ptr = 0xff;

	//normal method //read modify and write
	*ptr &= ~(1 << 7);		//clear 7th bit position

	//bit band method
	*ptr = 0xff;		//RESET VALUE TO 0XFF
	//uint_t* alias_addr = 0x22000000 + (32 * (0x20000200-0x20000000)) + 7*4;
	uint8_t* alias_addr = (uint8_t*)(ALIAS_BASE + (32 * (0x20000200-BITBAND_BASE)) + 7*4);

	//CLEARING 7TH BIT OF ADDRESS 0x20000200
	*alias_addr = 0;


	for(;;);
}

